djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.conf.urls.static import static
from django.urls import path
from djangoProject import settings as SETTINGS

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/register_user/', views.register_user, name='register_user'),
    path('accounts/login_user/', views.login_user, name='login_user'),
    path('accounts/logout_user/', views.logout_user, name='logout_user'),
    path('accounts/profile/', views.view_profile, name='view_profile'),
    path('accounts/profile/update/', views.update_profile, name='update_profile'),
    path('accounts/profile/update_password/', views.update_password, name='update_password'),
    path('assignments/', views.assignments, name='assignments'),
    path('assignments/<int:assignment_id>/results/', views.assignment_results_list, name='assignment_results'),
    path('assignments/<int:assignment_id>/download/<int:assignment_result_id>', views.download_assignment_file, name='download_assignment_result_file'),
    path('assignments/<int:assignment_id>/submission/', views.assignment_submission, name='assignment_submission'),
    path('assignments/create/', views.assignment_create, name='assignment_create'),
    path('assignments/grade/', views.assignments_grade, name='assignments_grade'),
    path('morale/', views.morale, name='morale'),
]

home/models.py
from django.contrib.auth.models import AbstractUser
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from djangoProject import settings


class User(AbstractUser):
    profile_image = models.FileField(upload_to="profile_images", blank=True, null=True)
    is_teacher = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Assignment(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    description = models.CharField(max_length=500)
    due_date = models.DateTimeField()

    def __str__(self):
        return self.title


class AssignmentResult(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    submission_date = models.DateTimeField()
    file = models.FileField(upload_to="assignments", null=True)
    grade = models.FloatField(default=0, validators=[MinValueValidator(0.0), MaxValueValidator(100.0)])

    def __str__(self):
        return f"{self.user.username} submission for '{self.assignment.title}'"

    def get_letter_grade(self):
        if 90 <= self.grade <= 100:
            return "A+"
        elif 85 <= self.grade < 90:
            return "A"
        elif 80 <= self.grade < 85:
            return "A-"
        elif 75 <= self.grade < 80:
            return "B+"
        elif 70 <= self.grade < 75:
            return "B"
        elif 65 <= self.grade < 70:
            return "B-"
        elif 60 <= self.grade < 65:
            return "C+"
        elif 55 <= self.grade < 60:
            return "C"
        elif 50 <= self.grade < 55:
            return "C-"
        elif 40 <= self.grade < 50:
            return "D"
        elif 0 <= self.grade < 40:
            return "E"
        else:
            return "Invalid percentage"


class AssignmentResultViewQuerySet(models.QuerySet):
    def get_by_custom_fields(self, assignment_id, assignment_result_id):
        return self.filter(
            assignment_id=assignment_id,
            assignment_result_id=assignment_result_id
        )

    def get_unique_results(self):
        return self.distinct()


class AssignmentResultView(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    assignment_id = models.IntegerField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    due_date = models.DateTimeField()
    assignment_result_id = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    submission_date = models.DateTimeField()
    file = models.FileField(upload_to="assignments", blank=True, null=True)
    grade = models.FloatField()

    class Meta:
        managed = False  # No migrations will be created for this model
        db_table = 'assignment_result_view'  # Name of the database view

    objects = AssignmentResultViewQuerySet.as_manager()

    def get_letter_grade(self):
        if 90 <= self.grade <= 100:
            return "A+"
        elif 85 <= self.grade < 90:
            return "A"
        elif 80 <= self.grade < 85:
            return "A-"
        elif 75 <= self.grade < 80:
            return "B+"
        elif 70 <= self.grade < 75:
            return "B"
        elif 65 <= self.grade < 70:
            return "B-"
        elif 60 <= self.grade < 65:
            return "C+"
        elif 55 <= self.grade < 60:
            return "C"
        elif 50 <= self.grade < 55:
            return "C-"
        elif 40 <= self.grade < 50:
            return "D"
        elif 0 <= self.grade < 40:
            return "E"
        else:
            return "Invalid percentage"

    def get_status(self):
        time_difference = self.submission_date - self.due_date
        total_seconds = abs(time_difference.total_seconds())
        days = total_seconds // (24 * 3600)
        total_seconds %= (24 * 3600)
        hours = total_seconds // 3600
        total_seconds %= 3600
        minutes = total_seconds // 60

        if self.submission_date < self.due_date:
            status = "early"
        else:
            status = "late"

        return f"Submitted for grading<br>{int(days)} days {int(hours)} hours {int(minutes)} minutes {status}"

    def get_status_color(self):
        if self.submission_date < self.due_date:
            return "green"
        else:
            return "red"

templates/pages/assignment_create.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <div class="card">
        <form method="post" class="card-body text-center">
            {% csrf_token %}
            <h3 class="mb-4">Create new assignment</h3>
            {% if message %}
                <div class="text-danger">{{ message }}</div>
            {% endif %}
            {% for field in form %}
                <div class="input-group mb-3">
                    {{ field }}
                </div>
            {% endfor %}
            <button class="btn btn-primary shadow-2 mb-4" type="submit">Create</button>
            <a href="{% url 'assignments' %}" class="btn btn-outline-secondary mb-4">Back to assignments</a>
        </form>
    </div>
{% endblock content %}

templates/pages/assignment_list_teacher.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <div style="display: flex; justify-content: space-between; align-items: center">
        <h3>Assignments</h3>
        <h5>
        <a href="{% url 'assignment_create' %}">
            <i class="feather icon-plus m-r-5"></i>
            Create new assignment</a>
            </h5>
    </div>

    <table class="table table-hover">
        <thead>
        <tr>
            <th>Assignment</th>
            <th>Due date</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for assignment in assignments %}
            <tr>
                <td><h6 class="m-0"><a href="{% url 'assignment_results' assignment.id %}">
                    {{ assignment.title }}
                </a></h6></td>
                <td>{{ assignment.due_date }}</td>
                <td>Coming soon...</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/pages/assignment_results_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block extrahead %}
    {{ block.super }}
    <script src="{% static 'assets/js/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'assets/plugins/jquery/js/jquery.min.js' %}"></script>
{% endblock extrahead %}

{% block content %}
    <div style="display: flex; justify-content: space-between; align-items: center">
        <h3>{{ assignment.title }}</h3>
        <h5><a href="{% url 'assignments' %}">
            <i
                    class="feather icon-arrow-left m-r-5"></i>
            Back to assignments</a></h5>
    </div>

    <table class="table table-hover">
        <thead>
        <tr>
            <th>User</th>
            <th>Submission</th>
            <th>Submission Time</th>
            <th>Status</th>
            <th>Mark</th>
            <th>Letter Grade</th>
        </tr>
        </thead>
        <tbody>
        {% for assignment_result in assignment.assignmentresult_set.all %}
            <tr data-assignment-result-id="{{ assignment_result.id }}">
                <td>
                    <h6 class="m-0"><img class="rounded-circle m-r-10" style="width:40px;"
                                         src="{% static 'assets/images/user/avatar-1.jpg' %}" alt="activity-user">
                        {{ assignment_result.user.first_name }} {{ assignment_result.user.last_name }}
                    </h6>
                </td>
                <td>
                    <h6 class="m-0">
                        <a href="{% url 'download_assignment_result_file' assignment.id assignment_result.id %}"
                           target="_blank">{{ assignment_result.file.name }}</a>
                    </h6>
                </td>
                <td>
                    <h6 class="m-0">{{ assignment_result.submission_date }}</h6>
                </td>
                <td>
                    <h6 class="m-0 text-c-{{ assignment_result.get_status_color }}">
                        {{ assignment_result.get_status }}
                    </h6>
                    <button class="btn btn-primary p-1 mt-2 open-grade-modal" data-assignment-result-id="{{ assignment_result.id }}" data-toggle="modal" data-target="#gradeModal" data-user-name="{{ assignment_result.user.get_full_name }}">
                        Grade
                    </button>
                </td>
                <td>
                    <h6 class="m-0">{{ assignment_result.grade }}%</h6>
                </td>
                <td>
                    <h6 class="m-0">{{ assignment_result.get_letter_grade }}</h6>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- The Modal -->
    <div class="modal fade" id="gradeModal" tabindex="-1" aria-labelledby="gradeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h5 class="modal-title" id="gradeModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <!-- Modal Body -->
                <div class="modal-body">
                    <form id="gradeForm">
                        {% csrf_token %}
                        <input type="hidden" name="assignment_result_id" id="assignmentResultIdInput">
                        <div class="form-group">
                            <label for="gradeInput">Grade</label>
                            <input type="number" class="form-control" id="gradeInput" name="grade" step="0.01" min="0" max="100" required>
                            <div id="gradeError" class="text-danger"></div>
                        </div>
                    </form>
                </div>
                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="submitGrade">Submit</button>
                </div>
            </div>
        </div>
    </div>


    <div style="height: 500px; max-height: 500px">
        <canvas id="gradeChart" width="500" height="500"></canvas>
    </div>
    <script>
    // Lil bit of ChatGPT
    $(document).ready(function(){
        var assignmentResultId;

        // handle open modal
        $('.open-grade-modal').on('click', function() {
            var userName = $(this).data('user-name');
            $('#gradeModalLabel').text('Enter Grade for ' + userName);
            assignmentResultId = $(this).data('assignment-result-id');
            $('#gradeForm input[name="assignment_result_id"]').val(assignmentResultId);
            $('#gradeInput').val('');
            $('#gradeError').text('');
        });

        // Handle form submission
        $('#submitGrade').click(function(){
            var grade = $('#gradeInput').val();
            var regex = /^\d+(\.\d{1,2})?$/; // 2 decimal place check
            if(grade !== "" && !isNaN(grade) && grade >= 0 && grade <= 100 && regex.test(grade)){
                var formData = $('#gradeForm').serialize();

                $.ajax({
                    url: '{% url "assignments_grade" %}',
                    method: 'POST',
                    data: formData,
                    success: function(response) {
                        if(response.success) {
                            var row = $('tr[data-assignment-result-id="' + assignmentResultId + '"]');
                            row.replaceWith(response.row_html);

                            $('#gradeModal').modal('hide');
                            $('#gradeInput').val('');
                            $('#gradeError').text(''); 
                        } else {
                            $('#gradeError').text('Failed to submit grade.');
                        }
                    },
                    error: function() {
                        $('#gradeError').text('Failed to submit grade.');
                    }
                });
            } else {
                $('#gradeError').text('Please enter a valid grade between 0 and 100.');
            }
        });
    });
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var ctx = document.getElementById('gradeChart').getContext('2d');
            var assignmentData = {{ data|safe }}
            console.log(assignmentData)

            var letterGrades = {
                'A+': 0, 'A': 0, 'A-': 0,
                'B+': 0, 'B': 0, 'B-': 0,
                'C+': 0, 'C': 0, 'C-': 0,
                'D': 0, 'E': 0
            };

            assignmentData.forEach(function (item) {
                var grade = item.grade;
                if (grade >= 90) {
                    letterGrades['A+']++;
                } else if (grade >= 85) {
                    letterGrades['A']++;
                } else if (grade >= 80) {
                    letterGrades['A-']++;
                } else if (grade >= 75) {
                    letterGrades['B+']++;
                } else if (grade >= 70) {
                    letterGrades['B']++;
                } else if (grade >= 65) {
                    letterGrades['B-']++;
                } else if (grade >= 60) {
                    letterGrades['C+']++;
                } else if (grade >= 55) {
                    letterGrades['C']++;
                } else if (grade >= 50) {
                    letterGrades['C-']++;
                } else if (grade >= 40) {
                    letterGrades['D']++;
                } else {
                    letterGrades['E']++;
                }
            });

            // Prepare data for Chart.js
            var labels = Object.keys(letterGrades);
            var data = Object.values(letterGrades);

            var myChart = new Chart(ctx, {
                type: 'bar',
                responsive: false,
                data: {
                    labels: labels,
                    datasets: [{
                        label: 'Grade Distribution',
                        data: data,
                        backgroundColor: 'rgba(54, 162, 235, 0.2)',
                        borderColor: 'rgba(54, 162, 235, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    maintainAspectRatio: false,
                    scales: {
                        yAxes: [{
                            beginAtZero: true,
                            ticks: {
                                stepSize: 1
                            },
                            scaleLabel: {
                                display: true,
                                labelString: 'Count',
                                fontStyle: 'bold',
                                fontSize: '16'
                            }
                        }],
                        xAxes:[{
                            scaleLabel: {
                                display: true,
                                labelString: 'Grade',
                                fontStyle: 'bold',
                                fontSize: '16'
                            },
                         }]
                    }
                }
            });
        });
    </script>
{% endblock content %}

templates/pages/assignment_results_student.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <div>
        <h3>Assignments</h3>
        <form method="get" action="{% url 'assignments' %}" class="form-inline">
            <div class="form-group mb-2">
                <input type="text" name="search" class="form-control" placeholder="Search by title" value="{{ search_query }}">
            </div>
            <button type="submit" class="btn btn-primary mb-2 ml-2" style="font-size: 1.25em; padding: 7.375px;">
                <i class="feather icon-search"></i>Search
            </button>
        </form>
    </div>

    <table class="table table-hover">
        <thead>
        <tr>
            <th>Assignment</th>
            <th>Due date</th>
            <th>Submission Time</th>
            <th>Status</th>
            <th>Mark</th>
            <th>Letter Grade</th>
            <th>Submission</th>
            <th>Feedback</th>
        </tr>
        </thead>
        <tbody>
        {% for assignment in assignments %}
            {% if assignment.assignment_result_id == -1 %}
                <tr>
                    <td><h6 class="m-0">
                        <a href="{% url 'assignment_submission' assignment.assignment_id %}">{{ assignment.title }}</a>
                    </h6></td>
                    <td>{{ assignment.due_date }}</td>
                    <td>-</td>
                    <td>Not Submitted</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
            {% else %}
                <tr>
                    <td>
                        <h6 class="m-0">
                            <a href="{% url 'assignment_submission' assignment.assignment_id %}">{{ assignment.title }}</a>
                        </h6>
                    </td>
                    <td>
                        <h6 class="m-0">{{ assignment.due_date }}</h6>
                    </td>
                    <td>
                        <h6 class="m-0">{{ assignment.submission_date }}</h6>
                    </td>
                    <td>
                        <h6 class="m-0 text-c-{{ assignment.get_status_color }}">
                            {{ assignment.get_status }}
                        </h6>
                    </td>
                    <td>
                        <h6 class="m-0">{{ assignment.grade }}%</h6>
                    </td>
                    <td>
                        <h6 class="m-0">{{ assignment.get_letter_grade }}</h6>
                    </td>
                    <td>
                        <a href="{% url 'download_assignment_result_file' assignment.assignment_id assignment.assignment_result_id %}"
                           target="_blank">Download</a>
                    </td>
                    <td>
                        No feedback yet!
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/pages/assignment_submission.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <h3>{{ assignment.title }}</h3>
    <h5>Due: {{ assignment.due_date }}</h5>

    <p>{{ assignment.description }}</p>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary shadow-2 mb-4">Submit assignment</button>
        <a href="{% url 'assignments' %}" class="btn btn-outline-secondary mb-4">Back to assignments</a>
    </form>
{% endblock content %}

templates/pages/assignment_submission_no_submit.html
{% extends 'layouts/base.html' %}
{% load static %}
{#{% block extrahead %}#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.css">#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.js"></script>#}
{#{% endblock extrahead %}#}

{% block content %}
    <h3>{{ assignment.title }}</h3>
    <h5>Due: {{ assignment.due_date }}</h5>
    <p>{{ assignment.description }}</p>
    <div class="text-danger">
        <p>Submission only available to students</p>
    </div>
    <a href="{% url 'assignments' %}">Back to assignments</a>
{% endblock content %}

templates/pages/auth-signin.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <form method="post" class="card-body text-center">
                    {% csrf_token %}
                    <div class="mb-4">
                        <i class="feather icon-unlock auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Login</h3>
                    {% if message %}
                    <div class="text-danger">{{ message }}</div>
                    {% endif %}
{#                    {% if form.non_field_errors %}#}
{#                        {% for error in form.non_field_errors %}#}
{#                            <span class="text-danger d-block my-3">{{ error }}</span>#}
{#                        {% endfor %}#}
{#                    {% endif %}#}
                    {% for field in form %}
                    <div class="input-group mb-3">
                        {{ field }}
                    </div>
                    {% endfor %}
{#                    <div class="form-group text-left mt-4">#}
{#                        <div class="checkbox checkbox-fill d-inline">#}
{#                            <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">#}
{#                            <label for="checkbox-fill-a1" class="cr"> Save Details</label>#}
{#                        </div>#}
{#                    </div>#}
                    <button class="btn btn-primary shadow-2 mb-4" type="submit">Login</button>
                    <p class="mb-0 text-muted">Don’t have an account? <a href="{% url 'register_user' %}">Signup</a></p>
                </form>
            </div>
        </div>
    </div>

    <label class="d-none">
        <i class="icon feather icon-sun" id="theme-indicator"></i>
        <input type="checkbox" id="theme-switch" class="d-none">
    </label>

{% endblock content %}

templates/pages/auth-signup.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <form method="post" class="card-body text-center">
                    {% csrf_token %}
                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Sign up</h3>
                    {% for field in form %}
                    <div class="input-group mb-3">
                        {{ field }}
                    </div>
                    <span class="text-danger d-block text-left">{{ field.errors }}</span>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary shadow-2 mb-4">Sign up</button>
                    <p class="mb-0 text-muted">Already have an account? <a href="{% url 'login_user' %}"> Log in</a></p>
                </form>
            </div>
        </div>
    </div>


    <label class="d-none">
        <i class="icon feather icon-sun" id="theme-indicator"></i>
        <input type="checkbox" id="theme-switch" class="d-none">
    </label>

{% endblock content %}

templates/pages/morale.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <div class="card p-2 shadow-2">
        <h1>Morale Booster</h1>
        <form method="post" class="mb-3">
            {% csrf_token %}
            <input class="form-control" name="api_url" id="api_url" value="https://api.thecatapi.com/v1/images/search" disabled>
            {{ api_url }}
        </form>
        <img id="catImage" alt="A cute cat" style="max-width: 100%; height: auto;">
    </div>
    <script>
        const apiUrl =  document.getElementById("api_url").value;
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

        function getCatImage() {
            fetch("{% url 'morale' %}", {
                method: "POST",
                headers: {
                'Content-Type':'application/json',
                'X-CSRFToken':csrftoken
                }, 
                body: JSON.stringify({'api_url':apiUrl}) 
                
            })
                .then(response => response.json())
                .then(data => {
                    const imageUrl = data[0].url;
                    document.getElementById('catImage').src = imageUrl;
                })
                .catch(error => {
                    console.error('Error fetching the cat image:', error);
                });
        }
        getCatImage();
    </script>
{% endblock content %}

templates/pages/profile.html
{% extends "layouts/base.html" %}
{% load static %}
{% block content %}
    <div class="auth-wrapper">
    <div class="auth-content">
        <div class="auth-bg">
            <span class="r"></span>
            <span class="r s"></span>
            <span class="r s"></span>
            <span class="r"></span>
        </div>
        <div class="card">
            <div class="d-flex align-items-center justify-content-center flex-column">
                <div class="pro-head">
                    {% if user.profile_image %}
                        <img src="{{ user.profile_image.url }}" alt="profile image"
                             class="img-radius">
                    {% else %}
                        <img src="{% static 'assets/images/user/avatar-1.jpg' %}" alt="profile image"
                             class="img-radius">
                    {% endif %}
                </div>
                <h2 class="mb-3">{{ user.get_full_name }}</h2>
                <h5>Username: {{ user.get_username }}</h5>
                <h5>Email: {{ user.email }}</h5>
                <a class="btn btn-secondary shadow-2 mb-4 mt-4" href="{% url 'update_profile' %}">Update Profile</a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/pages/update_password.html
{% extends "layouts/base.html" %}
{% load static %}
{% block content %}
<div class="auth-wrapper">
    <div class="auth-content">
        <div class="auth-bg">
            <span class="r"></span>
            <span class="r s"></span>
            <span class="r s"></span>
            <span class="r"></span>
        </div>
        <div class="card">
            <form method="post" enctype="multipart/form-data" class="card-body text-center">
                {% csrf_token %}
                <div class="d-flex align-items-center justify-content-center flex-column">
                    <div class="w-50 p-3"><h3>Update Password</h3></div>
                </div>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <span class="text-danger d-block my-3">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                {% for field in form %}
                    <div class="form-group mb-3">
                        {{ field }}
                    </div>
                    <span class="text-danger d-block text-left">{{ field.errors }}</span>
                {% endfor %}
                <a class="btn btn-secondary shadow-2 mb-4" href="{% url 'view_profile' %}">Cancel</a>
                <button class="btn btn-primary shadow-2 mb-4" type="submit">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/pages/update_profile.html
{% extends "layouts/base.html" %}
{% load static %}
{% block content %}
<div class="auth-wrapper">
    <div class="auth-content">
        <div class="auth-bg">
            <span class="r"></span>
            <span class="r s"></span>
            <span class="r s"></span>
            <span class="r"></span>
        </div>
        <div class="card">
            <form method="post" enctype="multipart/form-data" class="card-body text-center">
                {% csrf_token %}
                <div class="d-flex align-items-center justify-content-center flex-column">
                    <div class="w-50 p-3">
                        {% if user.profile_image %}
                            <img src="{{ user.profile_image.url }}" alt="profile image"
                                 class="img-fluid rounded-circle">
                        {% else %}
                            <img src="{% static 'assets/images/user/avatar-1.jpg' %}" alt="profile image"
                                 class="img-fluid rounded-circle">
                        {% endif %}
                    </div>
                </div>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <span class="text-danger d-block my-3">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                {% for field in form %}
                    <div class="form-group mb-3">
                        {{ field }}
                    </div>
                {% endfor %}
                <a class="btn btn-secondary shadow-2 mb-4" href="{% url 'update_password' %}">Update Password</a>
                <button class="btn btn-primary shadow-2 mb-4" type="submit">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}